export const DefaultersData = [
    {
        name: "Aisha Khan",
        image: "/src/assets/students-images/img.png",
        description: "Missed tuition payment",
        fine: "Rs. 1200",
        date: "2025-03-02",
    },
    {
        name: "Ali Ahmed",
        image: "/src/assets/students-images/img.png",
        description: "Library fine",
        fine: "Rs. 850",
        date: "2025-03-15",
    },
    {
        name: "Zara Ali",
        image: "/src/assets/students-images/img.png",
        description: "Class absence",
        fine: "Rs. 700",
        date: "2025-03-20",
    },
    {
        name: "Omar Butt",
        image: "/src/assets/students-images/img.png",
        description: "Transport fee unpaid",
        fine: "Rs. 1100",
        date: "2025-04-05",
    },
    {
        name: "Sara Sheikh",
        image: "/src/assets/students-images/img.png",
        description: "Late fee submission",
        fine: "Rs. 950",
        date: "2025-02-28",
    },
    {
        name: "Bilal Malik",
        image: "/src/assets/students-images/img.png",
        description: "Damaged lab equipment",
        fine: "Rs. 1800",
        date: "2025-03-01",
    },
    {
        name: "Nadia Raza",
        image: "/src/assets/students-images/img.png",
        description: "Dress code violation",
        fine: "Rs. 400",
        date: "2025-03-18",
    },
    {
        name: "Kamran Hussain",
        image: "/src/assets/students-images/img.png",
        description: "Sports fee pending",
        fine: "Rs. 1050",
        date: "2025-04-04",
    },
    {
        name: "Hina Siddiqui",
        image: "/src/assets/students-images/img.png",
        description: "Unreturned library book",
        fine: "Rs. 600",
        date: "2025-03-21",
    },
    {
        name: "Faisal Ansari",
        image: "/src/assets/students-images/img.png",
        description: "Exam malpractice",
        fine: "Rs. 2000",
        date: "2025-02-27",
    },
    {
        name: "Mehwish Akhtar",
        image: "/src/assets/students-images/img.png",
        description: "Uniform violation",
        fine: "Rs. 500",
        date: "2025-03-30",
    },
    {
        name: "Junaid Chaudhry",
        image: "/src/assets/students-images/img.png",
        description: "Classroom disturbance",
        fine: "Rs. 750",
        date: "2025-04-01",
    },
    {
        name: "Sana Mirza",
        image: "/src/assets/students-images/img.png",
        description: "Tuition dues pending",
        fine: "Rs. 1400",
        date: "2025-03-10",
    },
    {
        name: "Rizwan Qureshi",
        image: "/src/assets/students-images/img.png",
        description: "Transport fee pending",
        fine: "Rs. 980",
        date: "2025-03-25",
    },
    {
        name: "Farah Awan",
        image: "/src/assets/students-images/img.png",
        description: "Library fine",
        fine: "Rs. 660",
        date: "2025-04-06",
    },
    {
        name: "Imran Rana",
        image: "/src/assets/students-images/img.png",
        description: "ID card lost",
        fine: "Rs. 300",
        date: "2025-02-25",
    },
    {
        name: "Kiran Shah",
        image: "/src/assets/students-images/img.png",
        description: "Missed practical exam",
        fine: "Rs. 1600",
        date: "2025-03-12",
    },
    {
        name: "Shahid Yousaf",
        image: "/src/assets/students-images/img.png",
        description: "Unauthorized absence",
        fine: "Rs. 950",
        date: "2025-04-03",
    },
    {
        name: "Naima Javed",
        image: "/src/assets/students-images/img.png",
        description: "Behavioral issue",
        fine: "Rs. 700",
        date: "2025-03-08",
    },
    {
        name: "Waqas Iqbal",
        image: "/src/assets/students-images/img.png",
        description: "Lost textbook",
        fine: "Rs. 500",
        date: "2025-03-29",
    },
    {
        name: "Saima Rehman",
        image: "/src/assets/students-images/img.png",
        description: "Activity fee unpaid",
        fine: "Rs. 820",
        date: "2025-04-08",
    },
    {
        name: "Yasir Aziz",
        image: "/src/assets/students-images/img.png",
        description: "Project submission delay",
        fine: "Rs. 950",
        date: "2025-03-05",
    },
    {
        name: "Amber Farooq",
        image: "/src/assets/students-images/img.png",
        description: "Missed sports day",
        fine: "Rs. 440",
        date: "2025-03-16",
    },
    {
        name: "Zeeshan Nasir",
        image: "/src/assets/students-images/img.png",
        description: "Unpaid fine from last term",
        fine: "Rs. 1250",
        date: "2025-02-29",
    },
    {
        name: "Bushra Pervez",
        image: "/src/assets/students-images/img.png",
        description: "Bus card misuse",
        fine: "Rs. 600",
        date: "2025-03-23",
    },
];
